dist: trusty
sudo: required

language: php


services:
  - docker

#addons:
#  apt:
#    update: true

cache: false

env:
  global:
#    - SYMFONY_PHPUNIT_DIR="$HOME/symfony-bridge/.phpunit"
#    - SYMFONY_PHPUNIT_VERSION="6.3"
#     - DOCKERIZE_VERSION=v0.6.1


matrix:
  fast_finish: true
  include:
    - php: 7.2
#    - php: nightly
#  allow_failures:
#    - php: nightly

before_install:
  - '[[ "$TRAVIS_PHP_VERSION" == "nightly" ]] || phpenv config-rm xdebug.ini'
  #  - composer self-update
  #  - sudo rm /usr/local/bin/docker-compose
  # - wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz
  # - sudo tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz
  # - sudo rm dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz


install:
    - composer install --no-progress --no-interaction --no-suggest
    - cp ./app/config/parameters.yml.dist ./app/config/parameters.yml
    - docker-compose up -d --build
    - docker container exec compo-plan-dockerize dockerize -wait tcp://db:3306 -wait http://nginx -timeout 20s
    # - sleep 15
    - docker container exec compo-plan-php php bin/console doctrine:schema:update --force -vvv
    - docker container exec compo-plan-php php bin/console fos:user:create root --super-admin test@test.ru 11111111
    - docker-compose down

#  - ./vendor/bin/simple-phpunit install

script:
  # this checks that the YAML config files contain no syntax errors
  - ./bin/console lint:yaml app
  - ./bin/console lint:yaml src

  # this checks that the Twig template files contain no syntax errors
  - ./bin/console lint:twig src
  - ./bin/console lint:twig app/Resources

  # this checks that the application doesn't use dependencies with known security vulnerabilities
  - ./bin/console security:check --end-point=http://security.sensiolabs.org/check_lock

  # this checks that the composer.json and composer.lock files are valid
  # --strict
  - composer validate

  # this checks that Doctrine's mapping configurations are valid
  #  - ./bin/console doctrine:schema:validate --skip-sync -vvv --no-interaction

  #  - ./vendor/bin/simple-phpunit
  # this checks that the source code follows the Symfony Code Syntax rules
  #  - '[[ "$TRAVIS_PHP_VERSION" == "nightly" ]] || ./vendor/bin/php-cs-fixer fix --diff --dry-run -v'



