services:
#    collaborator.example:
#        class: Compo\CollaboratorBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    collaborator.admin.collaborator:
        class: Compo\CollaboratorBundle\Admin\CollaboratorAdmin
        arguments: [~, Compo\CollaboratorBundle\Entity\Collaborator, CollaboratorBundle:CollaboratorAdmin]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Collaborator }

    collaborator.admin.group:
        class: Compo\CollaboratorBundle\Admin\GroupAdmin
        arguments: [~, Compo\CollaboratorBundle\Entity\Group, CollaboratorBundle:GroupAdmin]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Group }
