services:
#    department.example:
#        class: Compo\DepartmentBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    department.admin.department:
        class: Compo\DepartmentBundle\Admin\DepartmentAdmin
        arguments: [~, Compo\DepartmentBundle\Entity\Department, DepartmentBundle:DepartmentAdmin]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Department }
